package dao;
// Generated 25 janv. 2017 00:17:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Borne generated by hbm2java
 */
public class Borne  implements java.io.Serializable {


     private Integer idBorne;
     private Station station;
     private Vehicule vehicule;
     private boolean etatBorne;
     private Set<Utilise> utilisesForBorneDepart = new HashSet<Utilise>(0);
     private Set<Utilise> utilisesForBorneArrivee = new HashSet<Utilise>(0);

    public Borne() {
    }

	
    public Borne(Station station, boolean etatBorne) {
        this.station = station;
        this.etatBorne = etatBorne;
    }
    public Borne(Station station, Vehicule vehicule, boolean etatBorne, Set<Utilise> utilisesForBorneDepart, Set<Utilise> utilisesForBorneArrivee) {
       this.station = station;
       this.vehicule = vehicule;
       this.etatBorne = etatBorne;
       this.utilisesForBorneDepart = utilisesForBorneDepart;
       this.utilisesForBorneArrivee = utilisesForBorneArrivee;
    }
   
    public Integer getIdBorne() {
        return this.idBorne;
    }
    
    public void setIdBorne(Integer idBorne) {
        this.idBorne = idBorne;
    }
    public Station getStation() {
        return this.station;
    }
    
    public void setStation(Station station) {
        this.station = station;
    }
    public Vehicule getVehicule() {
        return this.vehicule;
    }
    
    public void setVehicule(Vehicule vehicule) {
        this.vehicule = vehicule;
    }
    public boolean isEtatBorne() {
        return this.etatBorne;
    }
    
    public void setEtatBorne(boolean etatBorne) {
        this.etatBorne = etatBorne;
    }
    public Set<Utilise> getUtilisesForBorneDepart() {
        return this.utilisesForBorneDepart;
    }
    
    public void setUtilisesForBorneDepart(Set<Utilise> utilisesForBorneDepart) {
        this.utilisesForBorneDepart = utilisesForBorneDepart;
    }
    public Set<Utilise> getUtilisesForBorneArrivee() {
        return this.utilisesForBorneArrivee;
    }
    
    public void setUtilisesForBorneArrivee(Set<Utilise> utilisesForBorneArrivee) {
        this.utilisesForBorneArrivee = utilisesForBorneArrivee;
    }




}


