package dao;
// Generated 25 janv. 2017 00:17:46 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer idClient;
     private String nom;
     private String prenom;
     private Date dateNaissance;
     private Set<Reservation> reservations = new HashSet<Reservation>(0);
     private Set<Utilise> utilises = new HashSet<Utilise>(0);

    public Client() {
    }

	
    public Client(String nom, String prenom) {
        this.nom = nom;
        this.prenom = prenom;
    }
    public Client(String nom, String prenom, Date dateNaissance, Set<Reservation> reservations, Set<Utilise> utilises) {
       this.nom = nom;
       this.prenom = prenom;
       this.dateNaissance = dateNaissance;
       this.reservations = reservations;
       this.utilises = utilises;
    }
   
    public Integer getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public Date getDateNaissance() {
        return this.dateNaissance;
    }
    
    public void setDateNaissance(Date dateNaissance) {
        this.dateNaissance = dateNaissance;
    }
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }
    public Set<Utilise> getUtilises() {
        return this.utilises;
    }
    
    public void setUtilises(Set<Utilise> utilises) {
        this.utilises = utilises;
    }




}


