package dao;
// Generated 25 janv. 2017 00:17:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private ReservationId id;
     private Client client;
     private Vehicule vehicule;
     private Date dateEcheance;

    public Reservation() {
    }

	
    public Reservation(ReservationId id, Client client, Vehicule vehicule) {
        this.id = id;
        this.client = client;
        this.vehicule = vehicule;
    }
    public Reservation(ReservationId id, Client client, Vehicule vehicule, Date dateEcheance) {
       this.id = id;
       this.client = client;
       this.vehicule = vehicule;
       this.dateEcheance = dateEcheance;
    }
   
    public ReservationId getId() {
        return this.id;
    }
    
    public void setId(ReservationId id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Vehicule getVehicule() {
        return this.vehicule;
    }
    
    public void setVehicule(Vehicule vehicule) {
        this.vehicule = vehicule;
    }
    public Date getDateEcheance() {
        return this.dateEcheance;
    }
    
    public void setDateEcheance(Date dateEcheance) {
        this.dateEcheance = dateEcheance;
    }




}


