package dao;
// Generated 25 janv. 2017 00:17:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ReservationId generated by hbm2java
 */
public class ReservationId  implements java.io.Serializable {


     private int vehicule;
     private int client;
     private Date dateReservation;

    public ReservationId() {
    }

    public ReservationId(int vehicule, int client, Date dateReservation) {
       this.vehicule = vehicule;
       this.client = client;
       this.dateReservation = dateReservation;
    }
   
    public int getVehicule() {
        return this.vehicule;
    }
    
    public void setVehicule(int vehicule) {
        this.vehicule = vehicule;
    }
    public int getClient() {
        return this.client;
    }
    
    public void setClient(int client) {
        this.client = client;
    }
    public Date getDateReservation() {
        return this.dateReservation;
    }
    
    public void setDateReservation(Date dateReservation) {
        this.dateReservation = dateReservation;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReservationId) ) return false;
		 ReservationId castOther = ( ReservationId ) other; 
         
		 return (this.getVehicule()==castOther.getVehicule())
 && (this.getClient()==castOther.getClient())
 && ( (this.getDateReservation()==castOther.getDateReservation()) || ( this.getDateReservation()!=null && castOther.getDateReservation()!=null && this.getDateReservation().equals(castOther.getDateReservation()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getVehicule();
         result = 37 * result + this.getClient();
         result = 37 * result + ( getDateReservation() == null ? 0 : this.getDateReservation().hashCode() );
         return result;
   }   


}


