package dao;
// Generated 25 janv. 2017 00:17:46 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Station generated by hbm2java
 */
public class Station  implements java.io.Serializable {


     private Integer idStation;
     private BigDecimal latitude;
     private BigDecimal longitude;
     private String adresse;
     private Integer numero;
     private String ville;
     private Integer codePostal;
     private Set<Borne> bornes = new HashSet<Borne>(0);

    public Station() {
    }

	
    public Station(BigDecimal latitude, BigDecimal longitude) {
        this.latitude = latitude;
        this.longitude = longitude;
    }
    public Station(BigDecimal latitude, BigDecimal longitude, String adresse, Integer numero, String ville, Integer codePostal, Set<Borne> bornes) {
       this.latitude = latitude;
       this.longitude = longitude;
       this.adresse = adresse;
       this.numero = numero;
       this.ville = ville;
       this.codePostal = codePostal;
       this.bornes = bornes;
    }
   
    public Integer getIdStation() {
        return this.idStation;
    }
    
    public void setIdStation(Integer idStation) {
        this.idStation = idStation;
    }
    public BigDecimal getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }
    public BigDecimal getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public Integer getCodePostal() {
        return this.codePostal;
    }
    
    public void setCodePostal(Integer codePostal) {
        this.codePostal = codePostal;
    }
    public Set<Borne> getBornes() {
        return this.bornes;
    }
    
    public void setBornes(Set<Borne> bornes) {
        this.bornes = bornes;
    }




}


