package dao;
// Generated 25 janv. 2017 00:17:46 by Hibernate Tools 4.3.1



/**
 * Utilise generated by hbm2java
 */
public class Utilise  implements java.io.Serializable {


     private UtiliseId id;
     private Borne borneByBorneDepart;
     private Borne borneByBorneArrivee;
     private Client client;
     private Vehicule vehicule;

    public Utilise() {
    }

	
    public Utilise(UtiliseId id, Borne borneByBorneDepart, Client client, Vehicule vehicule) {
        this.id = id;
        this.borneByBorneDepart = borneByBorneDepart;
        this.client = client;
        this.vehicule = vehicule;
    }
    public Utilise(UtiliseId id, Borne borneByBorneDepart, Borne borneByBorneArrivee, Client client, Vehicule vehicule) {
       this.id = id;
       this.borneByBorneDepart = borneByBorneDepart;
       this.borneByBorneArrivee = borneByBorneArrivee;
       this.client = client;
       this.vehicule = vehicule;
    }
   
    public UtiliseId getId() {
        return this.id;
    }
    
    public void setId(UtiliseId id) {
        this.id = id;
    }
    public Borne getBorneByBorneDepart() {
        return this.borneByBorneDepart;
    }
    
    public void setBorneByBorneDepart(Borne borneByBorneDepart) {
        this.borneByBorneDepart = borneByBorneDepart;
    }
    public Borne getBorneByBorneArrivee() {
        return this.borneByBorneArrivee;
    }
    
    public void setBorneByBorneArrivee(Borne borneByBorneArrivee) {
        this.borneByBorneArrivee = borneByBorneArrivee;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Vehicule getVehicule() {
        return this.vehicule;
    }
    
    public void setVehicule(Vehicule vehicule) {
        this.vehicule = vehicule;
    }




}


