package dao;
// Generated 25 janv. 2017 00:17:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UtiliseId generated by hbm2java
 */
public class UtiliseId  implements java.io.Serializable {


     private int vehicule;
     private int client;
     private Date date;

    public UtiliseId() {
    }

    public UtiliseId(int vehicule, int client, Date date) {
       this.vehicule = vehicule;
       this.client = client;
       this.date = date;
    }
   
    public int getVehicule() {
        return this.vehicule;
    }
    
    public void setVehicule(int vehicule) {
        this.vehicule = vehicule;
    }
    public int getClient() {
        return this.client;
    }
    
    public void setClient(int client) {
        this.client = client;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UtiliseId) ) return false;
		 UtiliseId castOther = ( UtiliseId ) other; 
         
		 return (this.getVehicule()==castOther.getVehicule())
 && (this.getClient()==castOther.getClient())
 && ( (this.getDate()==castOther.getDate()) || ( this.getDate()!=null && castOther.getDate()!=null && this.getDate().equals(castOther.getDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getVehicule();
         result = 37 * result + this.getClient();
         result = 37 * result + ( getDate() == null ? 0 : this.getDate().hashCode() );
         return result;
   }   


}


