package dao;
// Generated 25 janv. 2017 00:17:46 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehicule generated by hbm2java
 */
public class Vehicule  implements java.io.Serializable {


     private Integer idVehicule;
     private TypeVehicule typeVehicule;
     private int rfid;
     private Integer etatBatterie;
     private String disponibilite;
     private BigDecimal latitude;
     private BigDecimal longitude;
     private Set<Borne> bornes = new HashSet<Borne>(0);
     private Set<Reservation> reservations = new HashSet<Reservation>(0);
     private Set<Utilise> utilises = new HashSet<Utilise>(0);

    public Vehicule() {
    }

	
    public Vehicule(TypeVehicule typeVehicule, int rfid, String disponibilite) {
        this.typeVehicule = typeVehicule;
        this.rfid = rfid;
        this.disponibilite = disponibilite;
    }
    public Vehicule(TypeVehicule typeVehicule, int rfid, Integer etatBatterie, String disponibilite, BigDecimal latitude, BigDecimal longitude, Set<Borne> bornes, Set<Reservation> reservations, Set<Utilise> utilises) {
       this.typeVehicule = typeVehicule;
       this.rfid = rfid;
       this.etatBatterie = etatBatterie;
       this.disponibilite = disponibilite;
       this.latitude = latitude;
       this.longitude = longitude;
       this.bornes = bornes;
       this.reservations = reservations;
       this.utilises = utilises;
    }
   
    public Integer getIdVehicule() {
        return this.idVehicule;
    }
    
    public void setIdVehicule(Integer idVehicule) {
        this.idVehicule = idVehicule;
    }
    public TypeVehicule getTypeVehicule() {
        return this.typeVehicule;
    }
    
    public void setTypeVehicule(TypeVehicule typeVehicule) {
        this.typeVehicule = typeVehicule;
    }
    public int getRfid() {
        return this.rfid;
    }
    
    public void setRfid(int rfid) {
        this.rfid = rfid;
    }
    public Integer getEtatBatterie() {
        return this.etatBatterie;
    }
    
    public void setEtatBatterie(Integer etatBatterie) {
        this.etatBatterie = etatBatterie;
    }
    public String getDisponibilite() {
        return this.disponibilite;
    }
    
    public void setDisponibilite(String disponibilite) {
        this.disponibilite = disponibilite;
    }
    public BigDecimal getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }
    public BigDecimal getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }
    public Set<Borne> getBornes() {
        return this.bornes;
    }
    
    public void setBornes(Set<Borne> bornes) {
        this.bornes = bornes;
    }
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }
    public Set<Utilise> getUtilises() {
        return this.utilises;
    }
    
    public void setUtilises(Set<Utilise> utilises) {
        this.utilises = utilises;
    }




}


